baseURL: ""
languageCode: "en-us"
title: "Mind on Paper"
author: "Sudarshan"
theme: "PaperMod"
description: "A short description of your blog for SEO and social media"
enableRobotsTXT: true

taxonomies:
  tag: "tags"
  category: "categories"

params:
  env: production
  homeInfoParams:
    title: "Stacked & Building"
    content: "Documenting what I’m building with the tools I love. React. Next.js. Payload. Growth — line by line."
  
  socialIcons:
    - name: "GitHub"
      url: "https://github.com/Sudarshan441"
    - name: "Twitter"
      url: "https://x.com/Sudarshan13160"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/sudarshan-pujari/"
    - name: "Email"
      url: "mailto:sudarshanpujari6@gmail.com"

  showHomeInfo: true
  showHomeInfoAvatar: true
  showHomeInfoName: true
  showHomeInfoBio: true
  showHomeInfoSocialLinks: true
  ShowPostNavLinks: true
  ShowReadingTime: true

  showToc: true
  showTags: true
  showCategories: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  showScrollToTop: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowShareButtons: true
  ShowWordCount: true
  assets:
    disableFingerprinting: true
  cover:
    linkFullImages: true

menu:
  main:
    - identifier: "categories"
      name: "Categories"
      url: "/categories/"
      weight: 1
    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 2
    - identifier: "archives"
      name: "Archives"
      url: "/archives/"
      weight: 3
