baseURL: "https://passionpen.netlify.app/" # Replace with your actual domain
languageCode: "en-us"
title: "Mind on Paper"
author: "Sudarshan"
theme: "PaperMod"
description: "Documenting what I’m building using React, Next.js, Payload CMS and more — line by line."
enableRobotsTXT: true
canonifyURLs: true

outputs:
  home:
    - HTML
    - JSON

taxonomies:
  tag: "tags"
  category: "categories"

params:
  env: production

  homeInfoParams:
    title: "Stacked & Building"
    content: "Documenting what I’m building with the tools I love. React. Next.js. Payload. Growth — line by line."
  
  socialIcons:
    - name: "GitHub"
      url: "https://github.com/Sudarshan441"
    - name: "Twitter"
      url: "https://x.com/Sudarshan13160"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/sudarshan-pujari/"
    - name: "Email"
      url: "mailto:sudarshanpujari6@gmail.com"

  showHomeInfo: true
  showHomeInfoAvatar: true
  showHomeInfoName: true
  showHomeInfoBio: true
  showHomeInfoSocialLinks: true

  ShowPostNavLinks: true
  ShowReadingTime: true
  showToc: true
  showTags: true
  showCategories: true
  showScrollToTop: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowShareButtons: true
  ShowWordCount: true

  assets:
    disableFingerprinting: true

  cover:
    linkFullImages: true
  search : true
  # SEO Enhancements
  seo:
    title: "Mind on Paper"
    description: "Technical blog by Sudarshan Pujari — thoughts, builds, and lessons on React, Next.js, Payload CMS, and more."
    image: "images/cover.png" # Path to an OpenGraph image (1200x630 preferred)
    twitterCard: "summary_large_image"
    twitterSite: "@Sudarshan13160"
    twitterCreator: "@Sudarshan13160"
    ogLocale: "en_US"
    schemaType: "Person"
    name: "Sudarshan Pujari"
    sameAs:
      - "https://github.com/Sudarshan441"
      - "https://x.com/Sudarshan13160"
      - "https://www.linkedin.com/in/sudarshan-pujari/"

menu:
  main:
    - identifier: "categories"
      name: "Categories"
      url: "/categories/"
      weight: 1
    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 2
    - identifier: "archives"
      name: "Archives"
      url: "/archives/"
      weight: 3
    - identifier: "search"
      name: "Search"
      url: "/search/"
      weight: 4
