baseURL: ""
languageCode: "en-us"
title: "Blogs"
theme: "PaperMod"

taxonomies:
  tag: "tags"
  category: "categories"

params:
  homeInfoParams:
    title: "Welcome to My Blog"
    content: "This is a personal blog where I write about various topics that interest me. Feel free to explore and connect with me!"
  
  socialIcons:
    - name: "GitHub"
      url: "https://github.com/username"
    - name: "Twitter"
      url: "https://twitter.com/username"
    - name: "LinkedIn"
      url: "https://linkedin.com/in/username"
    - name: "Email"
      url: "mailto:t2zQd@example.com"

  showHomeInfo: true
  showHomeInfoAvatar: true
  showHomeInfoName: true
  showHomeInfoBio: true
  showHomeInfoSocialLinks: true
  ShowPostNavLinks: true
  ShowReadingTime: true

  showToc: true
  showTags: true
  showCategories: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  showScrollToTop: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowShareButtons: true
  cover:
    linkFullImages: true

menu:
  main:
    - identifier: "categories"
      name: "Categories"
      url: "/categories/"
      weight: 1
    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 2
    - identifier: "archives"
      name: "Archives"
      url: "/archives/"
      weight: 3
